### ISSUE TITLE
`PULL_REQUEST_URL` env variable unbound

### ISSUE THREAD

**Issue by mazzy89** [kustomize-everything/action-promote#57]
when `promotion-method` is set to `push` the `PULL_REQUEST_URL` is never set it up https://github.com/kustomize-everything/action-promote/blob/f4cd6d811935df07a8e8192c1dbb917b7b7cafd6/src/commit-and-pull-request.sh#L137

As result since in the `entrypoint.sh` we have https://github.com/kustomize-everything/action-promote/blob/f4cd6d811935df07a8e8192c1dbb917b7b7cafd6/src/entrypoint.sh#L7, the promote action fails.

@highb could you confirm this bug? i was able to reproduce on my side.

**Comment by mazzy89** [comment]
@highb ping here

**Comment by highb** [comment]
Hey sorry my GH notifications are a mess. I've opened a PR that adds the push method to the test matrix and I'm not seeing it fail yet. Could you share how you are calling the action to help me repro it? I don't think that nounset should have an issue if a particular branch with unset values isn't being run so I thought that the pull request specific env var there would have been fine.

**Comment by highb** [comment]
Also @mazzy89 FYI Akuity has a new tool called Kargo that may be a good replacement for what I have written with this action, as well as the env rendering action. I'd appreciate your thoughts on using Kargo as a replacement for these actions. https://github.com/kustomize-everything/action-promote/issues/60

**Comment by mazzy89** [comment]
> Hey sorry my GH notifications are a mess. I've opened a PR that adds the push method to the test matrix and I'm not seeing it fail yet. Could you share how you are calling the action to help me repro it? I don't think that nounset should have an issue if a particular branch with unset values isn't being run so I thought that the pull request specific env var there would have been fine.

Here how the action is called:

```yaml
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          path: deployment
          ref: ${{ env.RELEASE_BRANCH }}

      - name: Promote built image to staging
        uses: mazzy89/action-promote
        with:
          target-repo: myorg/repo
          target-branch: ${{ env.RELEASE_BRANCH }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          working-directory: deployment
          promotion-method: push
          git-commit-user: ${{ github.actor }}
          git-commit-email: ${{ github.actor }}@users.noreply.github.com
          images: ${{ inputs.builds }}
```

> Also @mazzy89 FYI Akuity has a new tool called Kargo that may be a good replacement for what I have written with this action, as well as the env rendering action. I'd appreciate your thoughts on using Kargo as a replacement for these actions. https://github.com/kustomize-everything/action-promote/issues/60

I took a look. Although the tool looks very promising, at the moment seems like shooting with a bazooka to a fly. It requires running ArgoCD which in my case I do not plan to run it. A github action is a much lighter way to do promotion. The team is working to decouple it from ArgoCD and run it as standalone but they are not there yet.
